export const ACTION_LOAD_DATA = 'ACTION_LOAD_DATA';

export const ACTION_SAVE_DATA = 'ACTION_SAVE_DATA';

export const ACTION_SORT_DATA = 'ACTION_SORT_DATA';

export const ACTION_SAVE_SORT = 'ACTION_SAVE_SORT';

export const ACTION_SAVE_TOTAL_ITEMS = 'ACTION_SAVE_TOTAL_ITEMS';

export const ACTION_PAGINATE = 'ACTION_PAGINATE';
